name: PR Checks

# This workflow runs tests on pull requests targeting the main branch.

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Lint and Test (PR)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        # Checks out the code from the PR branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install --no-fund --no-audit
          cd webview-ui
          npm install --no-fund --no-audit

      - name: Lint
        run: |
          npm run lint

      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Tests with Xvfb
        run: |
          # Run standard tests and the package activation test
          xvfb-run -a sh -c "npm run test:all && npm run test:package"

      - name: Compile extension and webview
        run: npm run compile # This includes build:webview
