name: PR Checks

# This workflow runs tests on pull requests targeting the main branch.

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Lint and Test (PR)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Repository
        # Checks out the code from the PR branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci --no-fund --no-audit
          npm ci --no-fund --no-audit --prefix webview-ui

      - name: Lint
        run: |
          npm run lint

      - name: Install Xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Tests (Linux)
        if: runner.os == 'Linux'
        run: |
          xvfb-run -a sh -c "npm run test:all && npm run test:package"

      - name: Run Tests (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          npm run test:all
          npm run test:package

      - name: Compile extension and webview
        shell: bash
        run: npm run compile # This includes build:webview
